DESTINATION_PORTS = %W(Nhava\ Sheva Mundra Tuticorin Chennai)
TYPE = %W(TBL Haulage)
EQUIPMENT_TYPE = %W(20GP 40GP 40OT 40FR 20OT)
SHIPPING_LINE = %W(CMA\ CGM Maersk  Evergreen Safmarine PIL)
TRANSPORTERS = %W(1 2)